### PR TITLE
Add blob storage code to list for direct download

### PR DESCRIPTION
**Pull request by porta76**
Populating content list with "Blob Storage Connection Code" and Containername for direct download.

### CODE REVIEW

**Comment by SimonOfHH** [comment]
Hi @porta76 thanks for the PR. I'm reviewing it and will try to add your changes

**Comment by SimonOfHH** [comment]
Hi again @porta76 
I created a new branch ([dev-applychangesfromporta76-001](https://github.com/cosmoconsult/D365BC-Blob-Storage-API/tree/dev-applychangesfromporta76-001)) which contains the option to download a blob from the page similar to your approach. But I like to avoid adding the references to `table 89000 "AZBSA Blob Storage Connection"` anywhere else (besides it's own pages) in case people want to use their own setup somewhere else. 

Are you fine with these changes? Or do you miss anything?

**Comment by porta76** [comment]
Very nice. I actually wanted to to the same but struggled with my own eagerness to make the pull request.

It might be a good idea to remove procedures and global var from pages into the tables as well?

**Comment by SimonOfHH** [comment]
> It might be a good idea to remove procedures and global var from pages into the tables as well?

I didn't really want to use it that way, but everything I tried to do it only via Rec resulted in the loss of the "RequestObject"-variable on the Rec :( 
Let me merge my changes - maybe you find a way around this :) If so, just file a new pull request

**Pull request closed without merging**
